### ISSUE TITLE
Adding a subdirectory in shared project requires `src/` in import, module not found error

### ISSUE THREAD

**Issue by zakpatterson** [NiGhTTraX/ts-monorepo#269] opened 2022-07-27 07:02 UTC
See this commit: https://github.com/zakpatterson/ts-monorepo-test/commit/03ce61e07f0e5444c820eb8962844695000caab6

* Adding a subdirectory in foo requires `src/` to be in the import statement in bar
* After compiling code, paths are incorrect and module not found error happens when running with `node`.

Exploring https://github.com/jonkwheeler/tsconfig-replace-paths to fix paths after building

I'm running into this deploying a client/server app that has a shared package.

**Comment by NiGhTTraX** [comment] 2022-07-27 09:43
Duplicate of https://github.com/NiGhTTraX/ts-monorepo/issues/219#issuecomment-1080827724.

TS 4.7's has added support for ESM and [package.json#exports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing), but I've never managed to properly configure it in a monorepo, and keep the feature that code navigation should work without having to build everything at first.

**Closed by NiGhTTraX** 2022-07-27 09:43 UTC
