### ISSUE TITLE
Watch mode?

### ISSUE THREAD

**Issue by eduardoboucas** [NiGhTTraX/ts-monorepo#11] opened 2020-06-30 11:43 UTC
Hi,

First of all, thanks for this repo and accompanying article. Using TypeScript with Lerna feels way more complex than it should, and the resources you created really help with that complexity.

I'm curious to hear what you recommend for watch/development mode, such that you're listening for changes in any of the packages and automatically build them.

Thanks!

**Comment by NiGhTTraX** [comment] 2020-07-01 08:32
Hi @eduardoboucas and thanks for the question. The answer depends a bit on how you're building your packages.

If you're building with `tsc` (like in this repo) then you can just run `tsc --watch` in all the packages. You can use `lerna run <script> --parallel --stream` or the similar `yarn workspaces foreach --interlaced --parallel run <script>` command to watch all the packages at once.

If your packages have a `start` script then you can use [`ts-node-dev`](https://www.npmjs.com/package/ts-node-dev) together with [`tsconfig-paths`](https://www.npmjs.com/package/tsconfig-paths).

If you're bundling with `webpack` then you can use the corresponding [`tsconfig-paths-webpack-plugin`](https://www.npmjs.com/package/tsconfig-paths-webpack-plugin) package.

Hope that helps. I plan to add fully working examples to this repo covering all of the above, but until then I'll pin this issue so others can find the answer easily.

**Comment by eduardoboucas** [comment] 2020-07-01 09:44
Thanks @NiGhTTraX, that helps for sure!

**Comment by zefexdeveloper** [comment] 2020-08-24 01:49
@NiGhTTraX Thank you for this, it helped a lot. Let me ask you a question.
I managed to setup a monorepo based on yours and reading your articles but I'm having a problem. If I have a package, for instance `common` and this package has a folder called `config` with an `index.ts` file in it and I also have an `api` package with a `config` folder and an `index.ts` and this `api` package has `common` as dependency and I import, the `common` package doesn't read its own `config` folder but the `api` one, like it's not behaving like a scoped package. The only way I found to solve that was by compiling the actual `common` package before using on the `api` so it will read from `node_modules` as a package and get rid of `aliases`. Do you have any idea on how I can solve that? It's really boring having to be building the package over and over again when I have to change something and even using watch isn't something that should behave like this.
Something else I'd like to ask is regarding how to run. You mentioned that I can use `ts-node-dev` and I'm doing that but I will need to build the `common` package in order for it to work. Is there a way I can solve all this?

**Comment by NiGhTTraX** [comment] 2020-08-24 19:27
Hi, @zefexdeveloper. The scenario you're describing should work just fine if everything is set up like in this repo. Make sure your aliases point to the right locations; in [this repo](https://github.com/NiGhTTraX/ts-monorepo/blob/b3fcc2f6063a131f647b7aacd4f2c7d069306094/tsconfig.json#L7) they're set up to resolve `@nighttrax/common` to `packages/common/src`, I suspect in your case you'd want to change that to match your file structure.

> the common package doesn't read its own config folder but the api one

That sounds a bit suspicious. You can check the output of `tsc --noEmit --traceResolution` to understand what's happening and spot any potential mistakes.

> You mentioned that I can use ts-node-dev and I'm doing that but I will need to build the common package in order for it to work. Is there a way I can solve all this?

If you solve the problem above then `ts-node-dev` + `tsconfig-paths` should just work.

----

I'm going to close this issue since the original question about watch mode was answered and the repo now includes examples for popular tool integrations. @zefexdeveloper if you're still having trouble please open a new issue and include a small repo that reproduces your problem.

**Closed by NiGhTTraX** 2020-08-24 19:27 UTC

**Comment by calmonr** [comment] 2020-08-24 19:30
@NiGhTTraX Thank you very much, you rock. Keep up the good work and I will try to see if there's problems left and for sure create a small repo for that, but beforehand, thank you.
